name: instagram
description: Unofficial instagram clone made with flutter
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flukit:
    path: ../flukit
  flukit_icons:
    git:
      url: https://github.com/charles9904/flukit_icons.git
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: instagramSans
      fonts:
        - asset: assets/fonts/InstagramSans.ttf
          weight: 400
        - asset: assets/fonts/InstagramSansBold.ttf
          weight: 700
